version: '3'

services:
  db:
    container_name: postgre
    image: chat_database
    environment:
      POSTGRES_DB: telenote
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - chatbot:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${DB_USER} -U telebot" ]
    restart: always

  telebot:
    container_name: botnote
    image: botnote
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
    depends_on:
      db:
        condition: service_healthy
    restart: always

volumes:
  chatbot:
